name: Python Package Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and packaging
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade packaging

      - name: Install dependencies
        run: |
          pip install --use-feature=fast-deps -r requirements.txt
          pip install pytest pytest-cov pytest-pylint  # Install testing tools

      - name: Run tests with coverage and linting
        run: |
          pytest --pylint --cov
